// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Mxxf2sZjSSo5PldP8LLrYxPVBymlo3I',
    appId: '1:594421135780:web:a7d066ac0d88320ab6e931',
    messagingSenderId: '594421135780',
    projectId: 'fanar-pharmacy-solution',
    authDomain: 'fanar-pharmacy-solution.firebaseapp.com',
    storageBucket: 'fanar-pharmacy-solution.firebasestorage.app',
    measurementId: 'G-J2SY35S8B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEZgzBdX74xuCozDTXsNHN3MPEBg1akE',
    appId: '1:594421135780:android:ae6f740ac38ba6f0b6e931',
    messagingSenderId: '594421135780',
    projectId: 'fanar-pharmacy-solution',
    storageBucket: 'fanar-pharmacy-solution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFyS18alfMXueOcyDqEaJ7Vk9qGsyfoME',
    appId: '1:594421135780:ios:bdbaaf48998e33aeb6e931',
    messagingSenderId: '594421135780',
    projectId: 'fanar-pharmacy-solution',
    storageBucket: 'fanar-pharmacy-solution.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFyS18alfMXueOcyDqEaJ7Vk9qGsyfoME',
    appId: '1:594421135780:ios:bdbaaf48998e33aeb6e931',
    messagingSenderId: '594421135780',
    projectId: 'fanar-pharmacy-solution',
    storageBucket: 'fanar-pharmacy-solution.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Mxxf2sZjSSo5PldP8LLrYxPVBymlo3I',
    appId: '1:594421135780:web:ade6e1453d590228b6e931',
    messagingSenderId: '594421135780',
    projectId: 'fanar-pharmacy-solution',
    authDomain: 'fanar-pharmacy-solution.firebaseapp.com',
    storageBucket: 'fanar-pharmacy-solution.firebasestorage.app',
    measurementId: 'G-38XS176DY3',
  );

}